using BankingSolution.Domain.Entities;

namespace BankingSolution.Domain.Indicators;

public record struct AccountReplenishSucceeded(ReplenishAccountTransaction ReplenishAccountTransaction);
public record struct AccountWithdrawSucceeded(WithdrawAccountTransaction WithdrawAccountTransaction);
public record struct TransferSucceeded(WithdrawAccountTransaction WithdrawAccountTransaction);